<?php

namespace Ml\TransactionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CouchsurfingEvalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CouchsurfingEvalRepository extends EntityRepository
{
}
