<?php

namespace Ml\TransactionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EvalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvalRepository extends EntityRepository
{
}
