<?php

namespace Ml\ForumBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TopicUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TopicUserRepository extends EntityRepository
{
}
