<?php

namespace Ml\ServiceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CarpoolingUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarpoolingUserRepository extends EntityRepository
{
    public function findByOwner($user) {
        $reqRes = $this->createQueryBuilder("c")->leftJoin('c.carpooling', 'b')->where('b.user=:user')->setParameter('user', $user);
        
        return $reqRes->getQuery()->getResult();;
    }
}
