<?php

namespace Ml\ServiceBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SaleUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SaleUserRepository extends EntityRepository
{
    public function findByOwner($user) {
        $reqRes = $this->createQueryBuilder("c")->leftJoin('c.sale', 's')->where('s.user=:user')->setParameter('user', $user);
        
        return $reqRes->getQuery()->getResult();;
    }
}
